### PR TITLE
Searchbar for ingredients fixed

### LINKED ISSUE #145: Searchbar for ingredients doesn't work

### PR DESCRIPTION
**Pull request by gitlinde**
Bug fix by @rune2976 

I noticed our CustomCheckbox had been replaced by the old AdvancedSwitch in staging during a merge conflict, so I added back the CustomCheckbox too (in add_ingredients_page.dart).

Closes #145

### CODE REVIEW

File: foodplanner/lib/pages/add_ingredient_page.dart [hunk 1]
```diff
@@ -34,47 +34,97 @@ class _AddIngredientPageState extends State<AddIngredientPage> {
   late final AuthProvider authProvider;
 
   final List<Map<String, dynamic>> _ingredients = [];
+  final List<Map<String, dynamic>> _filteredIngredients = [];
   final TextEditingController _controller = TextEditingController();
-  final List<ValueNotifier<bool>> _controllers = [];
+
+  final Map<dynamic, ValueNotifier<bool>> _controllersById = {};
+
+  // final List<ValueNotifier<bool>> _controllers = [];
```
Comment (krestenlaust) [inline foodplanner/lib/pages/add_ingredient_page.dart]:
```suggestion
```

**Review by krestenlaust — APPROVED** [review]
Looks good. Haven't tested locally
